### ISSUE TITLE
Implement helping dialogs in screens '?'

### ISSUE THREAD

**Issue by Simmanz** [SwEnt-Group8/Street-work-app#147]
### Acceptance criteria :

- Each screen is displayed an helping action.
- Clicking the action display a modified CutsomDialog that is informative only.

### Tasks

- [x] Modify the CustomDialog to handle non-submittable state
- [x] Add `INFO` action
- [x] Set the pop-up for each screen
