### ISSUE TITLE
Implement TrainHub for the workout

### ISSUE THREAD

**Issue by tercierp** [SwEnt-Group8/Street-work-app#151]
## Description
Develop the first training mode screen for the Street Work App: Solo Training Mode. This feature allows users to track their workout sessions when training alone.

## Task list
- Create the training hub
  - [x] User can choose between 3 modes (Solo will be the only one completed in this PR)
  - [x] User can choos between differents activities (Planks will be the only one implemented in this PR
  - [x] Confirmation button (parameters)
- Link between Firestore and the frontend
  - [ ] Automatically save the session details in Firestore using `WorkoutData`.
